version: '3.6'

services:
  zookeeper:
    image: zookeeper
    container_name: dev_zookeeper
    restart: always
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: dev_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: dev_zookeeper:2181
      #Automatically creates a topic during kafka creation.
      #format comma separated <topicName>:<partitions>:<replicas>
      KAFKA_CREATE_TOPICS: "firstTopic:3:1, anyTopic:3:1, anotherTopic:2:1"
    depends_on:
      - zookeeper

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "dev_zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    depends_on:
      - zookeeper