version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: dev_zookeeper
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: dev_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: dev_zookeeper:2181
    depends_on:
      - zookeeper